//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruc.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://e-menu.sunat.gob.pe/cl-ti-itmenu/AutenticaMenuInternet.htm.
        /// </summary>
        internal static string Auth {
            get {
                return ResourceManager.GetString("Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://cel.reniec.gob.pe/valreg/valreg.do.
        /// </summary>
        internal static string DniCons {
            get {
                return ResourceManager.GetString("DniCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://cel.reniec.gob.pe/valreg/codigo.do.
        /// </summary>
        internal static string DniImage {
            get {
                return ResourceManager.GetString("DniImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://peru.rutificador.com/get_generic_ajax/.
        /// </summary>
        internal static string NombreCons {
            get {
                return ResourceManager.GetString("NombreCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/jcrS00Alias.
        /// </summary>
        internal static string RucCons {
            get {
                return ResourceManager.GetString("RucCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://e-consultaruc.sunat.gob.pe/cl-ti-itmrconsruc/captcha?accion=image.
        /// </summary>
        internal static string RucImage {
            get {
                return ResourceManager.GetString("RucImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.sunat.gob.pe/cl-ti-itmrconsmulruc/jrmS00Alias.
        /// </summary>
        internal static string RucMCons {
            get {
                return ResourceManager.GetString("RucMCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.sunat.gob.pe/cl-ti-itmrconsmulruc/captcha?accion=image.
        /// </summary>
        internal static string RucMImage {
            get {
                return ResourceManager.GetString("RucMImage", resourceCulture);
            }
        }
    }
}
